version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run: npm install
      - run: cd android && bundle install
      - run: cd android && ./gradlew androidDependencies
      - run: cd android && bundle exec fastlane internal
       