version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2021.10.2
    steps:
      - checkout
      - run: npm install
      - run: cd android && ./gradlew androidDependencies
      - run: cd android && fastlane internal
       