version: 2.1

jobs:
  build_app_job:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run: npm install
      - run: cd android && bundle install && bundle update fastlane
      - run: cd android && ./gradlew androidDependencies
      - run: cd android && bundle exec fastlane internal
       

workflows:
    version: 2
    build_app_workflow:
      jobs:
        - hold:
           type: approval
        - build_app_job:
            requires:
              - hold
            context:
              - canary-lab